print("Hello, World!")
print("This is a sample Python file.")
print("It contains multiple lines of code.")
print("Each line prints a different message.")
print("This is the last line of the file.")
print("Goodbye, World!")
print("End of the sample file.")
print("Thank you for reading this file.")
print("Have a great day!")
print("This is just a demonstration.")
print("Python is fun!")
print("Let's write some more lines.")
print("Almost done!")
print("Just a few more lines to go.")
print("This is line number 15.")
print("Line 16 is here.")